# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1),
        ),
    ]
